### ISSUE TITLE
Data cannot be downloaded from box.nju.edu.cn

### ISSUE THREAD

**Issue by UeFan** [njucckevin/SeeClick#13]
Dear authors,

I just found the data you provided cannot be found. For example https://box.nju.edu.cn/d/5b8892c1901c4dbeb715/ and https://box.nju.edu.cn/f/6a804cf190dd490a808f/

I was able to access those data yesterday. 

Another issue is that the web data in pretrain is really big (130GB) and I always got a downloading error due to long downloading time and the connection will be stopped after about 3 hours. Could you please split the data and reupload? Thank you very much.

**Comment by njucckevin** [comment]
Hi,

I think there's something wrong with nju.box because I also can not get it to work. I guess it'll be recovered soon.

For the large pre-training web data, I tried to split it to chunks and upload through [huggingface](https://huggingface.co/datasets/cckevinn/SeeClick-WebImgs). But it's quite slow for me now, I'm trying to speed up the upload process.
